language: ruby
sudo: required
dist: precise
warnings_are_errors: true
rvm:
  - 2.2
script:
  - pip install --user mkdocs
  - mkdocs build --clean
notifications:
  email:
    on_success: change
    on_failure: change

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY_SECURE
  skip_cleanup: true
  bucket: dev.cityofchicago.org
  local-dir: site/
  upload-dir: docs/lead-safe
  on:
    repo: Chicago/lead-safe-api-docs
    branch: master
