
# Site Information
site_name: Lead Safe API v0.5.0-alpha3
site_author: City of Chicago
site_description: Lead Free API Documentation
site_url: http://dev.cityofchicago.org/docs/lead-free

# Page Tree
pages:
- Home: index.md
- 'Terms of Service': 'tos.md'
- 'Apply for Lead Safe': 'apply.md'

# Copyright
copyright: Copyright &copy; 2016-2017 <a href="http://www.cityofchicago.org">City of Chicago</a> and licensed under <a href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International</a>.

# Repository Information
# repo_name: Chicago/open311-api-docs
# repo_url: http://github.com/Chicago/open311-api-docs

# Theme
theme_dir: 'theme/material'
site_favicon: 'assets/images/favicon.png'
extra:
  logo: 'assets/images/city-seal-inverse-small.png'
  palette:
    primary: 'blue'
    accent: 'red'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/ChicagoCDO'
    - type: 'github'
      link: 'https://github.com/Chicago'
    - type: 'envelope-o'
      link: 'mailto:developers@cityofchicago.org'
    - type: 'home'
      link: 'http://dev.cityofchicago.org'
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/extra.js'

# Google Analytics
# google_analytics:

# Extensions
markdown_extensions:
  - admonition
  - toc(permalink=true)
  - footnotes
